name: Python atividade4
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: install python packages
      run:
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        pip install requests
        pip install google-auth
        pip install google-cloud-storage
    - name: execute py script
      run: python python_names_storage.py
    - uses: stefanzweifel/git-auto-commit-action@v4